### ISSUE TITLE
REALLY small issue in Grid Mode

### ISSUE THREAD

**Issue by 1-scruff** [outsetini/Air-Classic#7]
Before I rant, the Classic Air skin is by far my favourite skin and I'm loving it to the point where I am unable to use other ones, so hats off to you for such a great skin!

Ok, so there's this tiny little bit of darker grey over games that you mouse over, as pictured [here](http://imgur.com/a/lK7CP).
(the second one is Just Cause 3 moused over)

I know it's SO ASTONISHINGLY SMALL and I shouldn't be writing this, but it really bugs me. Normally I just drag that slider at the bottom down and up and it fixes itself, but It would be great if it could be fixed somehow.
If there's just some sort of value somewhere in the files somewhere I can change, that'd be swell.

Thanks (or sorry if I've bugged you with this),
scruffy

**Comment by outsetini** [comment]
Oh man, I absolutely DESPISE this bug! I spent so much time back in the day trying to figure out how to fix it... Suffice to say, I failed in that battle and moved the new Air over to a completely different solution for the grid mode in order to avoid it.

I wish I had better news man, the only thing I was going to mention was the little trick about re-sizing but it sounds like you already figured that one out. Sorry!
